### ISSUE TITLE
Broken color codes on windows

### ISSUE THREAD

**Issue by carlosms** [src-d/go-log#15]
We replaced logrus with `go-log` in Engine and now the logs have broken coloring characters on windows:

![](https://user-images.githubusercontent.com/406916/56675212-da5dab00-66bb-11e9-9354-1391e11a3047.png)

Reported here https://github.com/src-d/engine/issues/456#issuecomment-486312335

**Comment by mcuadros** [comment]
fixed by https://github.com/src-d/go-log/pull/16

**Comment by carlosms** [comment]
After some testing the problem persists, exact same output in windows with 1.0.2
